apiVersion: v1
kind: Secret
metadata:
  name: grievous-secret
type: Opaque
data:
  username: Z2VuZXJhbA==
  password: a2Vub2Jp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grievous-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grievous
  template:
    metadata:
      labels:
        app: grievous
    spec:
      containers:
      - name: grievous
        image: mongo:6.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - echo
            - "hello"
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - echo
            - "hello"
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 27017
          hostPort: 27017
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   valueFrom: 
        #     secretKeyRef:
        #       name: grievous-secret
        #       key: username
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   valueFrom: 
        #     secretKeyRef:
        #       name: grievous-secret
        #       key: password
---
apiVersion: v1
kind: Service
metadata:
  name: grievous-service
spec:
  selector:
    app: grievous
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

