apiVersion: v1
kind: ConfigMap
metadata:
  name: kenobi-config
data:
  grievous-address: grievous-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kenobi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kenobi
  template:
    metadata:
      labels:
        app: kenobi
    spec:
      containers:
      - name: kenobi
        image: egrzeszczak/kenobi:1.0.10
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - echo
            - "hello"
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - echo
            - "hello"
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3000
        env:
        - name: NUXT_MONGO_ADDRESS
          valueFrom: 
            configMapKeyRef:
              name: kenobi-config
              key: grievous-address
---
apiVersion: v1
kind: Service
metadata:
  name: kenobi-service
spec:
  type: LoadBalancer
  selector:
    app: kenobi
  ports:
  - port: 3000
    targetPort: 3000
