name: Check K8s docs against Datree policies
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8sPolicyCheck:
    name: Check K8s files against policies
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout this repository
        uses: actions/checkout@v3
        
      - name: 2. Run Datree Policy Check on K8s files
        uses: datreeio/action-datree@main
        with:
          path: '*.yml'
          cliArguments: '--only-k8s-files'